language: ruby

env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=master"

rvm:
  - 2.1
  - 2.2
  - 2.3.1

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
  exclude:
    - rvm: 2.1
      env: RAILS_VERSION=master
    - rvm: 2.2
      env: RAILS_VERSION=master

before_install:
  - gem update bundler

before_script:
  - bundle exec rake app:db:setup

script: bundle exec rake spec
